#!/bin/sh
set -e

# Seed the ACL master include if the volume is empty (first boot)
if [ ! -f /etc/squid/acls/agents.conf ]; then
  cat > /etc/squid/acls/agents.conf <<'EOF'
# Auto-generated by EgressAclManager — do not edit manually.
# Per-agent ACL include files are listed below.
# This file is regenerated on every agent spawn/teardown.
EOF
  chown proxy:proxy /etc/squid/acls/agents.conf
fi

# Ensure log directory is writable
chown -R proxy:proxy /var/log/squid

exec squid --foreground -f /etc/squid/squid.conf
