/**
 * EgressAclManager — generates per-agent Squid ACL files from resolved
 * network capabilities. Writes ACL files to the shared egress_acls volume
 * and triggers Squid hot-reload on changes.
 *
 * Story 20.2
 * @see docs/epics/20-egress-proxy.md
 */

import fs from 'fs';
import path from 'path';
import Docker from 'dockerode';
import { Logger } from '../lib/logger.js';

const logger = new Logger('EgressAclManager');

/** Resolved network outbound list from CapabilityResolver */
export interface EgressCapabilities {
  outbound: string[];
}

export class EgressAclManager {
  private docker: Docker;
  /** Host-side path to the ACL directory (bind-mounted into both sera-core and the proxy) */
  private aclDir: string;
  /** Name of the proxy container for squid -k reconfigure */
  private proxyContainer: string;
  /** Track active agent ACL files: instanceId → filename */
  private activeAcls: Map<string, string> = new Map();

  constructor(docker: Docker, aclDir?: string, proxyContainer?: string) {
    this.docker = docker;
    this.aclDir = aclDir ?? process.env.EGRESS_ACL_DIR ?? '/egress/acls';
    this.proxyContainer = proxyContainer ?? 'sera-egress-proxy';
  }

  /**
   * Called after a container is spawned and inspected.
   * Writes a per-agent ACL file and regenerates the master include.
   */
  async onSpawn(
    instanceId: string,
    containerIp: string,
    capabilities: EgressCapabilities
  ): Promise<void> {
    const outbound = capabilities.outbound;
    if (outbound.length === 0) {
      // No outbound = networkMode 'none' — no ACL needed
      return;
    }

    const filename = `agent-${this.sanitize(instanceId)}.conf`;
    const filePath = path.join(this.aclDir, filename);
    const aclContent = this.generateAcl(instanceId, containerIp, outbound);

    fs.writeFileSync(filePath, aclContent, 'utf-8');
    this.activeAcls.set(instanceId, filename);
    logger.info(`ACL written for ${instanceId} (${containerIp}) → ${filename}`);

    this.regenerateMasterInclude();
    await this.reloadSquid();
  }

  /**
   * Called when a container is torn down.
   * Removes the per-agent ACL file and regenerates the master include.
   */
  async onTeardown(instanceId: string): Promise<void> {
    const filename = this.activeAcls.get(instanceId);
    if (!filename) return;

    const filePath = path.join(this.aclDir, filename);
    try {
      fs.unlinkSync(filePath);
    } catch {
      // File may already be gone
    }
    this.activeAcls.delete(instanceId);
    logger.info(`ACL removed for ${instanceId}`);

    this.regenerateMasterInclude();
    await this.reloadSquid();
  }

  /**
   * Register a blanket-allow ACL for sera-core itself.
   * Called once at startup so that web-fetch skill requests pass through.
   */
  async registerCoreAcl(coreIp: string): Promise<void> {
    const filename = 'sera-core.conf';
    const filePath = path.join(this.aclDir, filename);
    const safeName = 'sera_core';

    const lines = [
      `# sera-core blanket allow (web-fetch skill, internal requests)`,
      `acl ${safeName} src ${coreIp}/32`,
      `http_access allow ${safeName}`,
      '',
    ];

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
    // sera-core is not tracked in activeAcls — it's always present
    logger.info(`Core ACL written for ${coreIp}`);

    this.regenerateMasterInclude();
    await this.reloadSquid();
  }

  // ── ACL Generation ──────────────────────────────────────────────────────────

  private generateAcl(instanceId: string, containerIp: string, outbound: string[]): string {
    const safeName = `agent_${containerIp.replace(/\./g, '_')}`;
    const lines: string[] = [`# Agent: ${instanceId}`, `acl ${safeName} src ${containerIp}/32`];

    if (outbound.includes('*')) {
      // Wildcard — allow all destinations
      lines.push(`http_access allow ${safeName}`);
    } else {
      // Specific domain list
      const domainsAcl = `${safeName}_domains`;
      lines.push(`acl ${domainsAcl} dstdomain ${outbound.join(' ')}`);
      lines.push(`http_access allow ${safeName} ${domainsAcl}`);
    }

    // Explicit deny for this agent's IP — anything not matched above is blocked
    lines.push(`http_access deny ${safeName}`);
    lines.push('');

    return lines.join('\n');
  }

  // ── Master Include Regeneration ─────────────────────────────────────────────

  private regenerateMasterInclude(): void {
    const masterPath = path.join(this.aclDir, 'agents.conf');
    const lines: string[] = [
      '# Auto-generated by EgressAclManager — do not edit manually.',
      '# Per-agent ACL include files are listed below.',
      '# This file is regenerated on every agent spawn/teardown.',
    ];

    // Include sera-core ACL if it exists
    const coreAclPath = path.join(this.aclDir, 'sera-core.conf');
    if (fs.existsSync(coreAclPath)) {
      lines.push(`include /etc/squid/acls/sera-core.conf`);
    }

    // Include all active agent ACLs
    for (const filename of this.activeAcls.values()) {
      lines.push(`include /etc/squid/acls/${filename}`);
    }

    lines.push('');
    fs.writeFileSync(masterPath, lines.join('\n'), 'utf-8');
  }

  // ── Squid Reload ────────────────────────────────────────────────────────────

  private async reloadSquid(): Promise<void> {
    try {
      const container = this.docker.getContainer(this.proxyContainer);
      const exec = await container.exec({
        Cmd: ['squid', '-k', 'reconfigure'],
        AttachStdout: true,
        AttachStderr: true,
      });
      await exec.start({ hijack: true, stdin: false });
      logger.info('Squid reconfigured');
    } catch (err: unknown) {
      // Proxy may not be running (graceful degradation)
      logger.warn('Failed to reconfigure Squid (proxy may not be running):', err);
    }
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────

  /** Sanitize instance ID for use in filenames */
  private sanitize(id: string): string {
    return id.replace(/[^a-zA-Z0-9_-]/g, '_');
  }

  /** Get the number of active ACLs (for testing/monitoring) */
  get activeCount(): number {
    return this.activeAcls.size;
  }
}
