#!/usr/bin/env node
// Installs git hooks that delegate to npm scripts.
// Run once after cloning: npm run hooks:install

import { writeFileSync, chmodSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const hooksDir = join(root, '.git', 'hooks');

if (!existsSync(hooksDir)) {
  console.error('No .git/hooks directory found. Are you in the repo root?');
  process.exit(1);
}

const preCommit = `#!/bin/sh
# Generated by scripts/install-hooks.js — do not edit directly.
bun run pre-commit
`;

const hookPath = join(hooksDir, 'pre-commit');
writeFileSync(hookPath, preCommit, 'utf8');
chmodSync(hookPath, 0o755);
console.log('✓ pre-commit hook installed');
